[env:dfrobot_firebeetle2_esp32e]
platform = espressif32@6.6.0
framework = arduino
board = dfrobot_firebeetle2_esp32e
monitor_speed = 115200
upload_port = COM3
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DBOARD_HAS_PSRAM
	-D CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240
	-D CONFIG_FREERTOS_HZ=100
	-D CONFIG_ESP32_UART_RX_BUFFER_SIZE=768
	-mfix-esp32-psram-cache-issue
	-std=c++17
board_build.psram = true
board_build.flash_size = 16MB
extra_scripts = pre:extra_script.py
lib_deps = 
	bblanchon/ArduinoJson@^6.21.5
	milesburton/DallasTemperature@^3.9.1
	adafruit/DHT sensor library@^1.4.3
	adafruit/Adafruit Unified Sensor@^1.1.4
	ottowinter/ESPAsyncWebServer-esphome@^3.2.2
	paulstoffregen/OneWire@^2.3.5
	adafruit/RTClib@^2.0.2
	adafruit/Adafruit BusIO@^1.11.0
	fastled/FastLED @ ^3.9.6
	sparkfun/SparkFun Indoor Air Quality Sensor - ENS160@^1.1.0
	adafruit/Adafruit AS7341@^1.4.1
	4-20ma/ModbusMaster@^2.0.1
	plerup/EspSoftwareSerial@^8.2.0
	knolleary/PubSubClient@^2.8
monitor_filters = esp32_exception_decoder
